export const TASK_PROVIDERS_REQUEST = 'TASK_PROVIDERS_REQUEST';
export const TASK_PROVIDERS_SUCCESS = 'TASK_PROVIDERS_SUCCESS';
export const TASK_PROVIDERS_FAILURE = 'TASK_PROVIDERS_FAILURE';

export const TASK_PROVIDER_DETAILS_REQUEST = 'TASK_PROVIDER_DETAILS_REQUEST';
export const TASK_PROVIDER_DETAILS_SUCCESS = 'TASK_PROVIDER_DETAILS_SUCCESS';
export const TASK_PROVIDER_DETAILS_FAILURE = 'TASK_PROVIDER_DETAILS_FAILURE';
